Fix Mailing List
michiganhackers/mh-web-new pull request #116
Opened 2023-01-21 04:41 UTC by csaye

This pull request:
- Converts mailing list to a functional component instead of a class component
- Improves the styling of the mailing list and makes it fit in better with the rest of the site
- Prevents empty submissions to the mailing list by making the email field required

2023-01-21 20:40 UTC, KindaOK requested changes
Look good visually. Some of the underlying mechanics need change.

2023-01-21 20:40 UTC, KindaOK commented on src/components/MailingList/MailingList.jsx
>  import { StaticP } from "../../utility/ContentStyles.js";
Change to `utility/ContentStyles.js`

2023-01-21 20:40 UTC, KindaOK commented on src/components/MailingList/MailingList.jsx
> +    setSubmitted(true);
Clear these only if the response is okay. Backend is still down so it will be broken.

2023-01-21 20:40 UTC, KindaOK commented on src/components/MailingList/MailingList.jsx
> +        <StaticP> Successfully Added! </StaticP>
Should have alternative messages based on status code or server response.

2023-02-08 06:33 UTC, KindaOK commented on src/components/MailingList/MailingList.jsx
> +    border-top-left-radius: 16px;
We use 10px elsewhere

2023-02-11 23:57 UTC, csaye commented
Made the requested changes.

2023-02-12 00:05 UTC, KindaOK approved these changes

2023-02-12 00:05 UTC, merged