Footer
michiganhackers/mh-web-new pull request #121
Opened 2023-02-21 02:41 UTC by AkshayGupta8

Created Footer with updated icon sizing.

Override LinkComponents props with `font-size` attribute updated.

Added LinkComponent prop with default argument Link in ContactLinks.jsx

2023-02-21 03:13 UTC, KindaOK requested changes
Needs several changes. Read [this article](https://cbea.ms/git-commit/) for writing better commit messages as well.

2023-02-21 03:13 UTC, KindaOK commented on src/components/Footer.jsx
> +export default Footer;
This component isn't actually used anywhere. It should be at the bottom of all pages other than home.

2023-02-21 03:13 UTC, KindaOK commented on src/components/Contact/ContactLinks.jsx
> +export const Link = styled.a`
Don't export components from here for use in the footer. If you see that this component can be deduplicated, then extract it to `ContentStyles.js` and import it into these two components.

2023-02-21 03:13 UTC, KindaOK commented on src/components/Footer.jsx
> +const CustomLink = styled(Link)`
I don't think this is worth using inheritance for. While this is something we should improve, this is not the best place to start.

2023-02-21 03:13 UTC, KindaOK commented on src/components/Footer.jsx
> +// import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
Remove comments from imports

2023-02-21 03:13 UTC, KindaOK commented on src/components/Footer.jsx
> +import devices from "../utility/MediaQueries.js";
Use absolute imports instead of relative imports

2023-02-21 03:13 UTC, KindaOK commented on src/components/Footer.jsx
> +import ContactLinks, { Link } from "./Contact/ContactLinks";
Include file extensions in imports

2023-02-21 03:13 UTC, KindaOK commented on src/components/Footer.jsx
> +            <ContactLinks LinkComponent={CustomLink} />
This is probably a good idea given how many places we have this. However, this execution is not great. Refactor out the fragments into smaller components in a high-level file.

2023-02-21 03:13 UTC, KindaOK commented on src/components/Footer.jsx
> +    <FooterOuter>
Reduce the amount of wrappers if possible. These seem to be redundant.

2023-02-21 03:13 UTC, KindaOK commented on src/components/Footer.jsx
> +const ConnectWithUsFooter = styled.h1`
There should be no more than one `<h1>` per page. I don't think this should even be a heading given that this is generic content at the bottom of each page.

2023-02-21 03:13 UTC, KindaOK commented on src/components/Footer.jsx
> +                CONNECT WITH US
The actual design seems fine. The text and element itself is fairly large though.

2023-02-21 03:20 UTC, KindaOK requested changes

2023-02-21 03:20 UTC, KindaOK commented on src/components/Footer.jsx
> +const FooterOuter = styled.div`
The outermost wrapper should be a `<footer>`

2023-02-21 03:20 UTC, KindaOK commented on src/components/Footer.jsx
> +    background-color: rgba(238, 95, 48, 1);
Color should be hacker orange (see header)

2023-02-21 15:15 UTC, kgurushankar commented on src/components/Footer.jsx
> +import ContactLinks, { Link } from "./Contact/ContactLinks";
```suggestion
import devices from "../utility/MediaQueries.js";
import ContactLinks, { Link } from "./Contact/ContactLinks.jsx";
```

2023-03-23 00:10 UTC, KindaOK approved these changes

2023-03-23 00:14 UTC, merged